# Generated by Django 4.0.3 on 2022-03-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='image',
            field=models.ImageField(null=True, upload_to='business_partner_images'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(null=True, upload_to='testimonial_images/'),
        ),
    ]
