# Generated by Django 4.0.3 on 2022-03-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_businesspartner_image_alter_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=1500)),
                ('image', models.ImageField(null=True, upload_to='business_partner_images')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
