# Generated by Django 4.0.3 on 2022-03-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='designatiom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
