# Generated by Django 4.0.3 on 2022-03-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_rename_designatiom_message_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(null=True, upload_to='team_images'),
        ),
    ]
