# Generated by Django 4.0.3 on 2022-03-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_alter_businesspartner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(),
        ),
    ]
