# Generated by Django 4.0.3 on 2022-03-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=models.ImageField(null=True, upload_to='project_images/'),
        ),
    ]
