# Generated by Django 4.0.3 on 2022-03-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_alter_event_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='twitter',
            new_name='linkedin',
        ),
    ]
