# Generated by Django 4.0.4 on 2022-07-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0014_gallery_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image10',
            field=models.ImageField(null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image11',
            field=models.ImageField(null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image12',
            field=models.ImageField(null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image13',
            field=models.ImageField(null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image14',
            field=models.ImageField(null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image15',
            field=models.ImageField(null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image16',
            field=models.ImageField(null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image17',
            field=models.ImageField(null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image18',
            field=models.ImageField(null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image19',
            field=models.ImageField(null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image20',
            field=models.ImageField(null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image3',
            field=models.ImageField(null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image4',
            field=models.ImageField(null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image5',
            field=models.ImageField(null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image6',
            field=models.ImageField(null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image7',
            field=models.ImageField(null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image8',
            field=models.ImageField(null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image9',
            field=models.ImageField(null=True, upload_to='gallery_images/'),
        ),
    ]
